# Generated by Django 2.2.4 on 2019-11-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogposts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_image_header', models.CharField(max_length=200)),
                ('post_body', models.TextField()),
                ('post_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
