# Generated by Django 2.2.4 on 2019-11-25 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='blogposts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_image_header', models.CharField(max_length=200)),
                ('post_body', models.TextField()),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('post_views', models.IntegerField(default=0)),
                ('post_like', models.IntegerField(default=0)),
                ('post_count_comments', models.IntegerField(default=0)),
                ('post_author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagefile', models.ImageField(upload_to='blog/images')),
                ('imagedate', models.DateTimeField(auto_now=True)),
                ('imageuser', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.CharField(max_length=42)),
                ('comment_email', models.EmailField(max_length=75)),
                ('comment_comment', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now=True)),
                ('comment_moderated', models.BooleanField(default=False)),
                ('comment_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogposts')),
            ],
        ),
        migrations.CreateModel(
            name='adminExtraField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminFields_image', models.ImageField(upload_to='blog/images')),
                ('adminFields_bio', models.TextField()),
                ('adminFields_quote', models.TextField()),
                ('adminFields_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
