# Generated by Django 4.1.7 on 2023-02-21 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='adminFields_bio',
            new_name='user_bio',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='adminFields_image',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='adminFields_quote',
            new_name='user_quote',
        ),
    ]
