# Generated by Django 2.2.4 on 2019-11-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminextrafield',
            name='adminFields_image',
            field=models.ImageField(upload_to='blog/adminimages'),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='imagedate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
