# Generated by Django 2.2.4 on 2019-11-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminextrafield',
            name='adminFields_image',
            field=models.ImageField(upload_to='blog/adminimages'),
        ),
    ]
