# Generated by Django 2.2.4 on 2019-11-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='imagefile',
            field=models.ImageField(default='blog/images/default.png', upload_to=''),
        ),
    ]
