# Generated by Django 4.1.7 on 2023-03-05 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_adminfields_bio_user_user_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=25)),
                ('language_image', models.ImageField(upload_to='blog/images/languages')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_profile',
            field=models.ImageField(blank=True, null=True, upload_to='blog/adminimages'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_quote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogposts',
            name='post_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.languagetopic'),
        ),
    ]
