# Generated by Django 4.1.7 on 2023-03-05 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_languagetopic_alter_user_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagetopic',
            name='language_image',
            field=models.ImageField(upload_to='blog/images/languages', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webm', 'webp'])]),
        ),
    ]
