# Generated by Django 2.2.4 on 2019-11-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191112_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='imagefile',
            field=models.ImageField(default='blog/images/default.png', upload_to='blog/images'),
        ),
    ]
