# Generated by Django 2.2.4 on 2019-11-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191112_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='post_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='imagefile',
            field=models.ImageField(upload_to='blog/images'),
        ),
    ]
