# Generated by Django 2.2.4 on 2019-11-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191112_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='post_date',
            field=models.DateTimeField(),
        ),
    ]
