# Generated by Django 2.2.4 on 2019-11-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191115_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='imagefile',
            field=models.ImageField(upload_to='media/blog/images'),
        ),
    ]
