# Generated by Django 2.2.4 on 2019-11-23 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20191115_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='post_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogposts',
            name='post_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='images',
            name='imagedate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='images',
            name='imageuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='images',
            name='imagefile',
            field=models.ImageField(upload_to='blog/images'),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.CharField(max_length=42)),
                ('comment_email', models.EmailField(max_length=75)),
                ('comment_comment', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now=True)),
                ('comment_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogposts')),
            ],
        ),
    ]
