# Generated by Django 2.2.4 on 2019-11-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191123_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='post_like',
            field=models.IntegerField(default=0),
        ),
    ]
