# Generated by Django 2.2.4 on 2019-11-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogposts_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='post_count_comments',
            field=models.IntegerField(default=0),
        ),
    ]
